function make_dsl_baseline()
%MAKE_DSL_BASELINE Freeze the distributed-source-localization regression baseline.
%
%   Runs the NFT inverse solver (SCS and SBL) on the cortical demo fixture and
%   writes a compact digest of each estimate to
%   tests/fixtures/dsl_baseline/reference.mat, plus a PROVENANCE.md.
%
%   RE-BASELINE NOTE. This baseline is the current deterministic output of the
%   surviving SCS variant (patchz2, called directly on the raw leadfield -- the
%   only SCS core that still exists in source) and of the SBL path after fixing
%   its undefined-`ss` normalization bug. It is NOT the historical 2023
%   cortex_source_scs.mat: that file was produced by a compact SCS variant whose
%   core (patchz5/z6/d1) is lost, and no selection over the surviving solver's
%   iterates reproduces it (the solver's iterate trajectory itself is verified
%   bit-identical to the 2023 run's saved Jit.mat). The reference is therefore
%   re-created from scratch here, per the owner decision to canonicalize the
%   reproducible surviving pipeline. See PROVENANCE.md and .context/research.md.
%
%   Requires the fixture (env var NFT_DSL_DIR pointing at the cortical demo dir).
%   Run headless, e.g.:
%     NFT_DSL_DIR=/path/to/NFTplugin_demo_cortical \
%       matlab -batch "addpath('tests'); addpath('tests/baseline'); make_dsl_baseline"

  env = nft_test_env();
  assert(env.hasDsl, ['DSL fixture not found. Set NFT_DSL_DIR to the cortical demo ' ...
      'directory (holding s1_LFM.mat, ss_g10.mat, FSss_cor.mat, Node_area.mat, ' ...
      'jc_s1.sensors, Amica_comps_nft_sh.set).']);

  comps = 1:11;
  scratchRoot = fullfile(tempdir, sprintf('nft_dsl_baseline_%d', feature('getpid')));
  cleaner = onCleanup(@() rmIfExists(scratchRoot));

  fprintf('Running SCS (selection 3) on %d components...\n', numel(comps));
  scsOut = run_dsl(env, fullfile(scratchRoot, 'scs'), 3, comps);
  fprintf('  SCS solver: %.1f s\n', scsOut.dur);

  % Determinism check: the regression test relies on the solver being
  % reproducible, so verify it here before freezing the reference.
  scsOut2 = run_dsl(env, fullfile(scratchRoot, 'scs2'), 3, 1);
  detDelta = max(abs(scsOut.sourceJ(:, 1) - scsOut2.sourceJ(:, 1)));
  fprintf('  SCS determinism (comp 1, rerun): max|delta| = %.3g\n', detDelta);
  assert(detDelta == 0, 'SCS solver is not bit-reproducible; baseline would be unstable.');

  fprintf('Running SBL (selection 2) on %d components...\n', numel(comps));
  sblOut = run_dsl(env, fullfile(scratchRoot, 'sbl'), 2, comps);
  fprintf('  SBL solver: %.1f s\n', sblOut.dur);

  scs = dsl_digest(scsOut.sourceJ);
  sbl = dsl_digest(sblOut.sourceJ);
  meta = struct( ...
      'comps',        comps, ...
      'matlab',       version(), ...
      'arch',         computer('arch'), ...
      'gitSha',       localGitSha(env.repoRoot), ...
      'scsFval',      scsOut.fvalJ, ...
      'sblFval',      sblOut.fvalJ);

  outDir = fullfile(env.repoRoot, 'tests', 'fixtures', 'dsl_baseline');
  if exist(outDir, 'dir') ~= 7
      mkdir(outDir);
  end
  save(fullfile(outDir, 'reference.mat'), 'scs', 'sbl', 'meta', '-v7');
  writeProvenance(fullfile(outDir, 'PROVENANCE.md'), meta, scsOut, sblOut);
  fprintf('Wrote %s\n', fullfile(outDir, 'reference.mat'));
end

function sha = localGitSha(repoRoot)
  [st, out] = system(sprintf('git -C "%s" rev-parse HEAD', repoRoot));
  if st == 0
      sha = strtrim(out);
  else
      sha = 'unknown';
  end
end

function writeProvenance(path, meta, scsOut, sblOut)
  fid = fopen(path, 'w');
  c = onCleanup(@() fclose(fid));
  fprintf(fid, '# DSL regression baseline provenance\n\n');
  fprintf(fid, '- Generated by `tests/baseline/make_dsl_baseline.m`\n');
  fprintf(fid, '- MATLAB: %s\n', meta.matlab);
  fprintf(fid, '- Arch: %s\n', meta.arch);
  fprintf(fid, '- NFT git SHA: %s\n', meta.gitSha);
  fprintf(fid, '- Components: %s\n', mat2str(meta.comps));
  fprintf(fid, '- SCS solver time: %.1f s; SBL solver time: %.1f s\n', scsOut.dur, sblOut.dur);
  fprintf(fid, '\n## What this baseline is\n\n');
  fprintf(fid, ['This is a **re-baseline** of the distributed-source-localization inverse\n' ...
      'solvers to their current *deterministic* output, per the owner decision.\n\n']);
  fprintf(fid, ['- **SCS**: the surviving `patchz2` core called directly on the raw\n' ...
      '  leadfield. Its iterate trajectory is verified bit-identical to the 2023\n' ...
      '  reference run (`Jit.mat`), so the solver is preserved; only the final compact\n' ...
      '  source extraction of the lost 2023 variant (patchz5/z6/d1 core, no longer in\n' ...
      '  source anywhere) is not reproduced. This baseline freezes the reproducible\n' ...
      '  surviving pipeline instead.\n']);
  fprintf(fid, ['- **SBL**: the multi-resolution path after fixing the undefined-`ss`\n' ...
      '  normalization bug. With inputs shared with SCS, it reproduces the 2023\n' ...
      '  `cortex_source_sbl.mat` closely (per-component correlation ~0.78), which\n' ...
      '  cross-validates that the leadfield, kernels, electrode matching, and\n' ...
      '  component set are correct.\n\n']);
  fprintf(fid, 'The digest stores, per component: peak voxel id/value, L2 norm,\n');
  fprintf(fid, 'count of voxels above 5%% of peak, and the top-200 voxels (idx+val).\n');
end

function rmIfExists(d)
  if exist(d, 'dir') == 7
      rmdir(d, 's');
  end
end
